Charts
OpenGeoscience/uvdat pull request #13
Opened 2023-08-18 16:28 UTC by annehaley

This PR depends on #12 because both include new migration files, which should be applied sequentially.

I realized that chart data is different enough from map data that a new model should be created to represent them, so this PR does the following:

Server side
- [ ] Add a new model `Chart`
- [ ] Move the tide level data to a new file `charts.json` for population as a `Chart` object instead of a `Dataset` object
- [ ] Add tabs in the top of the UVDAT main drawer in the UI, allowing the user to toggle between viewing modes. Currently there are two tabs, "Map" and "Chart"
- [ ] Add functions to create and append to a `Chart` object any time the `compute_gcc` rest endpoint is accessed. The resulting chart data shows a point for every time gcc is computed.

Client side
- [ ] Add a ChartJS component to the main content area in the UI, shown when the view mode is switched to "Chart"
- [ ] Display a list of available `Chart` objects associated with the current City, shown when the view mode is switched to "Chart"
- [ ] Populate the ChartJS component when a `Chart` object is selected
- [ ] Add a widget for the user to control X-Axis slicing on the chart when the X range is large (like for the tide level data)
- [ ] Add an expansion panel to allow the user to look at the metadata on the selected `Chart` object

2023-08-23 23:18 UTC, annehaley commented
![image](https://github.com/OpenGeoscience/uvdat/assets/44912689/b6a97121-cb01-4dd8-9823-b5d163f957b0)
This is what the GCC chart looks like in the basic use case.  I used a targeted approach when turning nodes off, doing my best to chop the gcc in half. I used a random approach for turning nodes back on. The blue line shows how the gcc changed as I did this; large jumps in the line represent the loss or gain of a critical node.

![image](https://github.com/OpenGeoscience/uvdat/assets/44912689/9058c364-a83a-4b63-b3bc-08a203366dbd)
This is what the GCC chart looks like when I oscillate between turning nodes off and turning nodes on. The red line shows my transitioning between adding and subtracting disabled nodes.

2023-08-23 23:23 UTC, annehaley commented
![image](https://github.com/OpenGeoscience/uvdat/assets/44912689/bd1d52e8-32e6-4af6-ad5d-07ee24fd9505)

This is what the Daily Tide Levels chart looks like

2023-08-29 20:23 UTC, johnkit approved these changes
looks good outside the box.

2023-08-31 16:02 UTC, AlmightyYakob requested changes
Looks good overall, just a couple comments

2023-08-31 16:02 UTC, AlmightyYakob commented on web/src/components/MainDrawerContents.vue
> +        >
Just an FYI, the positioning of the refresh button makes it seem like it applies to the first item in the list. Maybe some padding or a line underneath this would clear things up?

2023-08-31 16:56 UTC, AlmightyYakob commented on web/src/components/MainDrawerContents.vue
> +        >
Sorry to further delay, but it seems it's impossible to click the refresh button without opening/closing the chart expansion panel

2023-09-01 14:57 UTC, AlmightyYakob approved these changes

2023-09-01 15:52 UTC, merged