Add DerivedRegions from Region Union/Intersection
OpenGeoscience/uvdat pull request #19
Opened 2023-09-12 15:16 UTC by AlmightyYakob

2023-09-21 18:10 UTC, AlmightyYakob commented
> > @annehaley lmk what you think of [`c48241a` (#19)](https://github.com/OpenGeoscience/uvdat/pull/19/commits/c48241a5f2aaa2b5b9d3dfe5773bd91c5f8c97fc). This is the rework of that function we talked about.
> 
> Yeah, I like that organization a lot more. However I do notice that the `createVectorLayer` function is only used for derived regions, and every Dataset with `geodata_file` defined uses `createVectorTileLayer`. There should be a separation between vector datasets that use tiles and vector datasets that don't. So if a Dataset has `vector_tiles_file` populated, it would use the tiled source. If it doesn't have a `vector_tiles_file` but does have a `geodata_file`, then a normal vector source should be used.
> 
> Unless, of course, these changes depend on your vector tile optimization. In that case, would every vector dataset use tiling?

I see what you mean. I do think they should be handled differently, but I'm confused on how it would work in this scenario. For a dataset that does _not_ have `vector_tiles_file` defined, but _does_ have `geodata_file` defined, and isn't a region dataset, what source would be used for the vector layer? Currently, the only way a vector layer is created from a dataset is through regions.

If we don't have a clear answer to the above question, I think it might be okay to just wait until the vector tiles optimization is merged in. In that case, derived regions may be the only "user" of vector layers, since we could just use vector tiles for everything else. We could even use vector tiles for derived regions as well, but that might be overkill.

What do you think?

2023-09-21 18:11 UTC, AlmightyYakob commented
Also, I'll work to resolve the currently conflicts since #20 is now merged.

2023-09-21 19:12 UTC, annehaley commented
> I see what you mean. I do think they should be handled differently, but I'm confused on how it would work in this scenario. For a dataset that does _not_ have `vector_tiles_file` defined, but _does_ have `geodata_file` defined, and isn't a region dataset, what source would be used for the vector layer? Currently, the only way a vector layer is created from a dataset is through regions.
> 
> If we don't have a clear answer to the above question, I think it might be okay to just wait until the vector tiles optimization is merged in. In that case, derived regions may be the only "user" of vector layers, since we could just use vector tiles for everything else. We could even use vector tiles for derived regions as well, but that might be overkill.
> 
> What do you think?

For Datasets, `vector_tiles_file` should be used as the input for a `VectorTileSource` if it exists. Else if `geodata_file` exists, it should be used as the input for a `VectorSource`. The contents of `geodata_file` are a geojson that can be used as vector data.

I definitely want to get your tiling optimization involved, but this doesn't need to depend on it. I still think the size of the geojson data should be our threshold for determining whether vector data should be tiled (whether that be a vector `Dataset`, `Region`, or `DerivedRegion`, though the latter two are not likely to exceed a size threshold). That way we don't end up creating too many `VectorTile` objects for vector data that doesn't need to be tiled.

2023-09-26 19:10 UTC, annehaley requested changes
This is just a first pass at a review; I haven't checked out the branch to try it yet. But These are just some questions and organization suggestions I had from just looking at the diff.

2023-09-26 19:50 UTC, AlmightyYakob commented on web/src/components/MainDrawerContents.vue
> -        >
The main issue I have with placing active layers first is that when layers are added/removed, it shifts everything underneath it, which is an annoying user experience. It seems to me there's two ways to solve this:

1. Make the "Active Layers" section a fixed height (or a tall min-height), allowing for scroll overflow
2. Place it below / aside from everything else

I'm okay with either, although I will say that since it's semantically different from everything else, I think separating "Active Layers" would be a good idea. Maybe a small overlay on the map? What do you think?

2023-09-26 19:52 UTC, AlmightyYakob commented on uvdat/core/views.py
> +    def create(self, request, *args, **kwargs):
I agree, I'll make that change.

2023-09-26 19:55 UTC, AlmightyYakob commented on uvdat/core/tasks/conversion.py
> +            original_projection = original_data.get('crs', {}).get('properties', {}).get('name')
I think it was just a styling change, since as far as I can tell, there's no reason to nest that in the `with open` block (it's independent of writing `geodata_file`).

2023-09-26 19:55 UTC, annehaley commented on web/src/components/MainDrawerContents.vue
> -        >
I like the idea of it being an overlay, but perhaps we should ensure that the user can minimize it if they don't want to see it. In that case, the main drawer would just consist of things that are available for the user to view. With that, can we change the title of the "Derived Regions" section to "Available Derived Regions"? Then all the sections in that drawer would have consistent naming and purpose.

2023-09-26 19:59 UTC, AlmightyYakob commented on web/src/components/OpenLayersMap.vue
I agree. There's two main sections of the template in that file: The tooltip, and the "context overlay". I think I'll factor each of those out into their own components, with more sub-components if necessary.

2023-09-26 20:00 UTC, AlmightyYakob commented on web/src/components/MainDrawerContents.vue
> -        >
That sounds good to me!

2023-09-28 16:05 UTC, AlmightyYakob commented on uvdat/core/views.py
> +    def create(self, request, *args, **kwargs):
[9cbf61d](https://github.com/OpenGeoscience/uvdat/pull/19/commits/9cbf61d60cf4d6009c36e4fb64eb287be5875ed9)

2023-09-28 18:27 UTC, AlmightyYakob commented on web/src/components/OpenLayersMap.vue
[`3c5a81d`](https://github.com/OpenGeoscience/uvdat/pull/19/commits/3c5a81d375d5ae6eff58dd068cccadfe98c6ca9c)

2023-09-29 15:45 UTC, AlmightyYakob commented on web/src/components/MainDrawerContents.vue
> -        >
This has been completed via [`fae72a9`](https://github.com/OpenGeoscience/uvdat/pull/19/commits/fae72a9d7c2a81095c6da65948d1eaa8bc8b1dba) and [`7f80b24`](https://github.com/OpenGeoscience/uvdat/pull/19/commits/7f80b245629bc8d03a56cf8e6eb8e902790e9cf5).

I had to shuffle the other region selection overlay around so please let me know what you think!

2023-10-03 13:47 UTC, annehaley commented
@AlmightyYakob I tried out the new Active Layers overlay and thought it could use a couple things:

- Tooltips on the icons so the user can understand their functions better (especially important for a button that clears all layers)
- Text to fill the component when there are no active layers to show
- Some spacing adjustments

I made these changes in [2e0b8d4](https://github.com/OpenGeoscience/uvdat/pull/19/commits/2e0b8d4ca74589c7d1fb663e1142b17cae987348), let me know what you think.

2023-10-03 17:55 UTC, annehaley reviewed
Thank you for accommodating my suggestions from the previous review :) 
The only things I thought of on this pass were minor. I made a few commits for small things, let me know what you think.

2023-10-03 17:55 UTC, annehaley commented on web/src/data.ts
The content of this file is good, just wondering if we can give it a more specific name / location? Maybe `web/src/map/utils.ts`?

2023-10-03 17:55 UTC, annehaley commented on web/src/layers.ts
I think this file can go in your new `map` directory, rather than at the `src` level.

2023-10-04 18:38 UTC, AlmightyYakob commented
> @AlmightyYakob I tried out the new Active Layers overlay and thought it could use a couple things:
> 
> * Tooltips on the icons so the user can understand their functions better (especially important for a button that clears all layers)
> * Text to fill the component when there are no active layers to show
> * Some spacing adjustments
> 
> I made these changes in [2e0b8d4](https://github.com/OpenGeoscience/uvdat/pull/19/commits/2e0b8d4ca74589c7d1fb663e1142b17cae987348), let me know what you think. Otherwise, I really like how this component looks, and I think it is a better place for this information.

Just checked it out, looks great! Thanks for those changes.

2023-10-04 19:10 UTC, AlmightyYakob commented on web/src/layers.ts
Both this and the `data.ts` file are used in other components outside of the `map` directory. Would you be okay leaving this as-is for now, and fixing it through https://github.com/OpenGeoscience/uvdat/issues/27?

2023-10-04 19:23 UTC, annehaley approved these changes

2023-10-04 19:26 UTC, merged