Simulations pane
OpenGeoscience/uvdat pull request #20
Opened 2023-09-14 13:34 UTC by annehaley

## Summary
The Simulations pane introduced in this PR allows the user to create `SimulationResult` objects in the database and view existing results. After picking a Simulation type, the user must specify all required inputs, then they may run the simulation. 

## Details
For this PR, only one Simulation type is implemented, called "Flood Scenario 1". Simulation types (not to be conflated with `SimulationResult`s) are not database objects. Rather, they exist as a hard-coded mapping of celery tasks. The simulation types populate the side-panel under "Available Simulations."
![image](https://github.com/OpenGeoscience/uvdat/assets/44912689/f642e5ff-b2af-4839-9cad-52dc9102ac39)

(Side note: this PR also switches the order of the "Available Layers" and "Active Layers" panels for consistency with the other panels' organization)

When the user selects a simulation type, the simulations pane appears for the selected type. The pane has two tabs: a tab to create a new `SimulationResult` object, and a tab to view existing ones. The tab to create a new one allows the user to specify all the inputs required for the selected simulation type. Once all required inputs are specified, the user may run the simulation.
![image](https://github.com/OpenGeoscience/uvdat/assets/44912689/2e929333-1087-4694-b649-615b3e36886f)

The request to run a simulation creates a `SimulationResult` object, which it returns to the client and sends into a Celery task to fill in the `output_data` field. While the celery task is running, the client shows the `SimulationResult` object's `input_args` and `modified_date`, as well as a spinner while the `output_data` is undefined. While the spinner is shown, the client polls the server every two seconds for an update. 
![image](https://github.com/OpenGeoscience/uvdat/assets/44912689/7bd180db-bb30-42e9-be96-6fcd44269650)

Once the celery task is complete, the client will receive the updated `output_data` on the target `SimulationResult` object and display it. In the case of "Flood Scenario 1", the output type is "network_failure_animation", so a specialized component called `NodeFailureAnimation` is displayed in the results section once `output_data` is defined. The node failure animation can be played forward or backward (with 1 second ticks) or the user can go directly to a step using the slider.
![image](https://github.com/OpenGeoscience/uvdat/assets/44912689/00031da6-aa46-46de-af40-57969d0df64e)

As the slider moves, the list of `deactivatedNodes` changes. The new value is equal to the node failure list, sliced to end on the index of the current tick. (On the second tick, `deactivatedNodes` contains 2 node ids.) As the list of deactivated nodes changes, the client sends a `computeGCC` request and updates the map with the response. This happens in the same manner as when the user manually updates the deactivated nodes.

The video attached below shows this behavior.

## Results

https://github.com/OpenGeoscience/uvdat/assets/44912689/4e3aa8fc-6c3d-4641-8270-822fe810c31a

2023-09-20 21:10 UTC, AlmightyYakob requested changes
Looks good overall, tested locally. Just have a few questions/concerns

2023-09-21 00:13 UTC, annehaley commented on uvdat/core/models.py
> +class SimulationResult(TimeStampedModel, models.Model):
Good point. I removed the redundant class for SimulationResult, Dataset, and City in [d58061d](https://github.com/OpenGeoscience/uvdat/pull/20/commits/d58061d61eb2d7b933b586658ab20681f3c78828)

2023-09-21 00:21 UTC, annehaley commented on uvdat/core/tasks/simulations.py
> +            simulation_id=simulation_id, input_args=kwargs
That's a good idea. I added a field `error_message` to the `SimulationResult` model so we can store and show any errors that occur from that check or otherwise: [9fb1640](https://github.com/OpenGeoscience/uvdat/pull/20/commits/9fb16402df97c2f1cd69d6eb0d41485d12bd4165)

I added the check within the simulation, though, because that's when we actually retrieve the datasets associated with the args. We want to be sure that the Datasets exist and meet all criteria at the run time of the simulation. What do you think?

2023-09-21 00:22 UTC, annehaley commented on uvdat/core/tasks/simulations.py
> +        return []
As of [9fb1640](https://github.com/OpenGeoscience/uvdat/pull/20/commits/9fb16402df97c2f1cd69d6eb0d41485d12bd4165), this case will save an error message to the result object so the user will see the failure.

2023-09-21 00:27 UTC, annehaley commented on uvdat/core/tasks/simulations.py
> +        sim_result, created = SimulationResult.objects.get_or_create(
Yes, it was my intention that `simulation_id` and `input_args` would be unique together to avoid duplicate objects. The user would be overwriting the previous results each time it is run (though most likely the new result would be the same).
I added a db constraint to this effect in [3f60dd8](https://github.com/OpenGeoscience/uvdat/pull/20/commits/3f60dd857b841d2e80a3bb37dcf2f42f4d68ee16)

2023-09-21 00:46 UTC, annehaley commented on web/src/api/rest.ts
> +  return (await apiClient.get("cities")).data;
Thank you for pointing this out. I had thought it was some dependency update and I didn't think too much of it, so I just went with it. But since you pointed out that it's not happening on master, I investigated further.
It turns out it was due to the change I'd made in settings.py to allow unauthenticated POST requests. In overwriting `configuration.REST_FRAMEWORK`, I had overwritten some important defaults. The change I made in [6cf524a](https://github.com/OpenGeoscience/uvdat/pull/20/commits/6cf524a74e89cdff0b2533a3c72680507bad2120) avoids this and gives us pagination back.

2023-09-21 02:17 UTC, annehaley commented
Note: I realized that `SimulationResult`s should also reference the City as their context (so similar simulations in different cities don't get confused). This change was made in [1cd52b8](https://github.com/OpenGeoscience/uvdat/pull/20/commits/1cd52b8cdcc5bfd926b3bc6ea54dd73645f3053f)

2023-09-21 15:56 UTC, AlmightyYakob commented on uvdat/core/tasks/simulations.py
> +            simulation_id=simulation_id, input_args=kwargs
I think that's a good approach :+1:

2023-09-21 16:30 UTC, AlmightyYakob commented on uvdat/core/models.py
> +        )
For the future, the Django [docs](https://docs.djangoproject.com/en/4.2/ref/models/options/#django.db.models.Options.unique_together) recommend using `UniqueConstraint` instead of `unique_together`.

2023-09-21 16:37 UTC, AlmightyYakob commented on uvdat/core/tasks/simulations.py
> +                    .all()
I think since we're already assuming that the type of an arg is `Dataset` via using `DatasetSerializer`, and since we have no counter examples yet, I think we can just remove the use of `arg.type` and hard-code `Dataset`.

2023-09-21 17:19 UTC, annehaley commented on uvdat/core/models.py
> +        )
Ok thanks. Changed in [c992c06](https://github.com/OpenGeoscience/uvdat/pull/20/commits/c992c067515f0fc9ca009ff08aca34a2cf360f90)

2023-09-21 17:46 UTC, AlmightyYakob approved these changes

2023-09-21 17:55 UTC, merged