Networks & File Items
OpenGeoscience/uvdat pull request #46
Opened 2024-08-02 15:00 UTC by annehaley

This PR consolidates the models changes from #45, which will be rebased on this branch.

2024-08-20 20:51 UTC, jjnesbitt requested changes

2024-08-20 20:51 UTC, jjnesbitt commented on uvdat/core/tasks/chart.py
> +        max_nodes += network.nodes.count()
You'll need to also import the `NetworkNode` model, but this will make just one query:

```suggestion
    max_nodes = NetworkNode.objects.filter(network__dataset=dataset).count()
```

2024-08-20 20:56 UTC, annehaley commented on uvdat/core/tests/test_load_roads.py
> +    )
Could you clarify the change here? I'm not able to tell the difference from the GH view

2024-08-20 20:58 UTC, jjnesbitt commented on uvdat/core/tests/test_load_roads.py
> +    )
Sorry, it just removes the excess blank line.

2024-08-20 21:28 UTC, jjnesbitt commented
Once the linting error is fixed I think this is good to go

2024-08-21 04:20 UTC, jjnesbitt approved these changes

2024-08-21 12:15 UTC, merged