Project Configuration UI
OpenGeoscience/uvdat pull request #66
Opened 2024-09-19 20:45 UTC by annehaley

2024-10-01 21:37 UTC, annehaley commented on web/src/storeFunctions.ts
>  }
Part of Faiza's design was the addition of the map location menus in the title section of each project's expansion panel: 
![image](https://github.com/user-attachments/assets/7f959fa2-992f-41f5-9d33-9c4276ec28de)
The user may hover over the geomarker icon to open the menu and click the option to snap to the project's default map position without selecting the project.

2024-10-01 21:42 UTC, annehaley commented on web/src/storeFunctions.ts
>  }
Changed in [cff13c4](https://github.com/OpenGeoscience/uvdat/pull/66/commits/cff13c4cdadaf97b27d3e1588ee93930aa90af81)

2024-10-03 19:55 UTC, jjnesbitt requested changes

2024-10-03 20:59 UTC, annehaley commented on uvdat/core/rest/project.py
> +    def partial_update(self, request, id):
You're right, this only made sense when `owner`, `collaborators`, and `followers` were fields on the Project model. I added your serializer and permissions endpoint in [d2bffde](https://github.com/OpenGeoscience/uvdat/pull/66/commits/d2bffde373e24062094136fdfeaf3fd6a46934d8). 

I removed the override of `partial_update`, but setting `dataset_ids` did not work. I had to change the key to `datasets` (though the value is still a list of IDs) in order for the changes to persist. And the client now needs a separate request to fetch the updated list of datasets in a project (the override had added that info to the response, but now we need to fetch it separately).

2024-10-03 20:59 UTC, annehaley commented on web/src/api/rest.ts
> +  data: object
Added in [d2bffde](https://github.com/OpenGeoscience/uvdat/pull/66/commits/d2bffde373e24062094136fdfeaf3fd6a46934d8)

2024-10-03 21:07 UTC, annehaley commented on web/src/storeFunctions.ts
> +export function setMapCenter(project: Project | undefined) {
Changed in [ccb3e39](https://github.com/OpenGeoscience/uvdat/pull/66/commits/ccb3e39786a591c939434b2cb8eccfda8ef25073)

2024-10-03 21:12 UTC, annehaley commented on web/src/store.ts
> +export const projectConfigMode = ref<boolean | string>(false);
Changed in [6ce1e6f](https://github.com/OpenGeoscience/uvdat/pull/66/commits/6ce1e6f43bb1e17533acab52aab858ce7c4afd5f)

2024-10-03 21:15 UTC, annehaley commented on uvdat/core/rest/project.py
Added in [80fe54e](https://github.com/OpenGeoscience/uvdat/pull/66/commits/80fe54eca12635cc9bc16a234fe1ba68ab329c06)

2024-10-03 21:19 UTC, annehaley commented on web/src/components/MainDrawerContents.vue
> +            <v-icon icon="mdi-map-marker-right" size="small" color="primary" />
Fixed in [d2ad119](https://github.com/OpenGeoscience/uvdat/pull/66/commits/d2ad11919dcb63a82e7e29e69709dbeac670cb39)

2024-10-03 21:35 UTC, annehaley commented on web/src/components/MainDrawerContents.vue
>      }
I'm somewhat partial to the `then` syntax because it acts as a visual wrapper around the asynchronous behavior. I try to only use the `async/await` syntax when necessary, like if the function needs to return something asynchronously. That's why `then` is used so often in other components I wrote.
This is more of a subjective preference, though, so I could be convinced to switch. If we do switch, we should update other occurrences of `then` for consistency.

2024-10-03 21:41 UTC, annehaley commented on web/src/components/MainDrawerContents.vue
> +    const saving: Ref<string | boolean> = ref(false);
Changed in [38d2cc9](https://github.com/OpenGeoscience/uvdat/pull/66/commits/38d2cc91200a0e723a6147f7caf67ec0cb4a40a5)

2024-10-03 21:45 UTC, jjnesbitt commented on web/src/components/MainDrawerContents.vue
>      }
Fair enough. Since what I suggested is functionally the same, feel free to reject it.

2024-10-03 22:15 UTC, jjnesbitt commented on uvdat/core/rest/project.py
> +    def partial_update(self, request, id):
If we need to include more data in the `datasets` field, we can do just that with the following line in `ProjectSerializer` (as well as re-ordering `DatasetSerializer` to above it):

```python
datasets = DatasetSerializer(many=True)
```
This will render the dataset as was being done in the `partial_update` method.

2024-10-04 18:23 UTC, annehaley commented on uvdat/core/rest/project.py
> +    def partial_update(self, request, id):
Ok, adding the dataset list to the project serializer lets us skip a couple of requests in the client. Updated in [028bf3a](https://github.com/OpenGeoscience/uvdat/pull/66/commits/028bf3a617de9849a3b5d55fa9739946f14b08a9).

2024-10-04 18:47 UTC, annehaley commented on uvdat/core/rest/project.py
> +    def partial_update(self, request, id):
Ah, it looks like that approach won't work if we want the field to be writeable. I got the following error when attempting to update the dataset list for a project:
```
AssertionError: The `.update()` method does not support writable nested fields by default. Write an explicit `.update()` method for serializer `uvdat.core.rest.serializers.ProjectSerializer`, or set `read_only=True` on nested serializer fields.
```
I rolled back [028bf3a](https://github.com/OpenGeoscience/uvdat/pull/66/commits/028bf3a617de9849a3b5d55fa9739946f14b08a9) because it fails tests.

2024-10-04 19:25 UTC, jjnesbitt commented on uvdat/core/rest/project.py
> +    def partial_update(self, request, id):
This was kind of irking me anyway: We should probably have two separate serializers, one for reading and one for writing. We have lots of computed fields, and you'd have the same issue if you tried to write to any of the computed fields. It's just that we happen to actually try to write to the `datasets` field. We can get around this pretty easily by defining a separate serializers (starting from my previous suggestion):
```python
class ProjectUpdateSerializer(serializers.ModelSerializer):
    class Meta:
        model = Project
        fields = '__all__'
```

and overriding this method in the ProjectViewSet class:
```
    def get_serializer_class(self) -> type[BaseSerializer]:
        if self.request.method not in SAFE_METHODS:
            return ProjectUpdateSerializer
        return super().get_serializer_class()
```

Let me know what you think.

2024-10-04 19:44 UTC, annehaley commented on uvdat/core/rest/project.py
> +    def partial_update(self, request, id):
Ok, I can do that, but it won't change the fact that we'll need an extra call to fetch a project's datasets after modifying them. The update endpoint will use the update serializer, which does not return the nested dataset objects. 
So ultimately, the nested `datasets` property on the read serializer wouldn't be used. The client uses the dataset list endpoint with a `project_id` query param instead (it fetches the datasets in a project more frequently than fetching the project itself).

2024-10-04 19:51 UTC, jjnesbitt commented on uvdat/core/rest/project.py
> +    def partial_update(self, request, id):
I'm pretty sure there's a way we can achieve the behavior we want, but at this point I don't feel it's worth the necessary effort. I imagine we'll refactor things in the not too distant future anyways, so it could be taken care of then.

2024-10-08 19:01 UTC, jjnesbitt commented on web/src/components/ProjectContents.vue
> +    }
Suggestion to make it a bit more readable and correctly typed. Testing locally it seems to behave as expected.

```suggestion
    function toggleDatasets({
      show,
      datasets,
    }: {
      show: boolean;
      datasets: Dataset[];
    }) {
      datasets.forEach(async (dataset) => {
        // Ensure layer index is set
        dataset.current_layer_index = dataset.current_layer_index || 0;
        if (dataset.map_layers === undefined) {
          dataset.map_layers = await getDatasetLayers(dataset.id);
          availableDatasetLayers.value = [
            ...availableDatasetLayers.value,
            ...dataset.map_layers,
          ];
        }

        // Try to get layer from dataset map layers array
        const layer = dataset.map_layers[dataset.current_layer_index];
        if (layer) toggleDatasetLayer(layer);

        // Ensure show and selected match
        const selected = selectedDatasetIds.value.includes(dataset.id);
        if (show && !selected) {
          selectedDatasets.value.push(dataset);
        } else if (!show && selected) {
          // Ensure dataset isn't current dataset and is filtered out from selected datasets
          if (currentDataset.value?.id === dataset.id) {
            currentDataset.value = undefined;
          }
          selectedDatasets.value = selectedDatasets.value.filter((d) => {
            d.id != dataset.id;
          });
        }
      });
    }
```

2024-10-08 19:15 UTC, jjnesbitt commented on web/src/storeFunctions.ts
>  }
I realized that the instant jump to locations is kind of jarring. We could smooth that out by using `flyTo` instead of `jumpTo`. The following code would implement that:

```typescript
export function setMapCenter(
  project: Project | undefined = undefined,
  jump = false
) {
  let center: [number, number] = [0, 30];
  let zoom = 1;
  if (project) {
    center = project.default_map_center;
    zoom = project.default_map_zoom;
  }

  const map = getMap();
  if (jump) {
    map.jumpTo({ center, zoom });
  } else {
    map.flyTo({ center, zoom, duration: 2000 });
  }
}
```

This adds the option to use `jumpTo` as well, since if we use `flyTo` when initially setting the map location, it will zoom out to the whole map view, which is a bit off. This would be accompanied with this change in `Map.vue`:

```typescript
    onMounted(() => {
      createMap();
      setMapCenter(undefined, true);
    });
```

2024-10-08 21:54 UTC, annehaley commented on web/src/components/ProjectContents.vue
> +    }
With this change applied, I am getting some unexpected behavior. First, I make a dataset visible, and next I click the gear icon in the Active Layers panel to make that the `currentDataset` and open the Options panel for that Dataset. Then, if I make that dataset invisible, the value for `currentDataset` is not cleared and the Options panel remains open.

2024-10-08 22:06 UTC, annehaley commented on web/src/components/ProjectContents.vue
> +export default {
Refactored in [7eb640c](https://github.com/OpenGeoscience/uvdat/pull/66/commits/7eb640c9114e88c2e944ba0698c9707b077e3ae1)

2024-10-08 22:07 UTC, annehaley commented on web/src/components/ProjectContents.vue
> +  setup(props: any) {
Resolved by switching to `script setup` syntax in [7eb640c](https://github.com/OpenGeoscience/uvdat/pull/66/commits/7eb640c9114e88c2e944ba0698c9707b077e3ae1)

2024-10-08 22:09 UTC, annehaley commented on web/src/storeFunctions.ts
>  }
Changed in [ce33080](https://github.com/OpenGeoscience/uvdat/pull/66/commits/ce3308061dbaec28c955cea79d996319c95579f6)

2024-10-10 14:41 UTC, jjnesbitt commented on web/src/components/ProjectContents.vue
> +    }
My bad, I've updated the suggestion. At some point we should really do some tech debt reduction in the client, specifically store/layer functions. There's so many things flying around and it's hard to tell what changes impact what parts of the code, since anywhere there could just be a vue `watch` call that does all sorts of things. I'll likely try to address that as a part of #27.

2024-10-10 15:09 UTC, annehaley commented on web/src/components/ProjectContents.vue
> +    }
Sounds good. I've tested out the updated suggestion, and it works as expected. I applied the suggestion in [754d1be](https://github.com/OpenGeoscience/uvdat/pull/66/commits/754d1beb89fd984a8097c1429a31e4ab311a2b05).

2024-10-10 16:27 UTC, jjnesbitt requested changes

2024-10-10 16:27 UTC, jjnesbitt commented on web/src/components/ProjectConfig.vue
> +      if (selectedProject.value?.id == projectToDelete.value?.id) {
I would highly encourage the use of `===` over `==` (as well as `!==` over `!=`) in pretty much all cases, since `==` does implicit type coercion, and can result in unexpected behavior. Unless you have a convincing argument otherwise, I'd suggest we eliminate it's use entirely going forward (although not necessarily in this PR, if that's too much of a lift).

2024-10-10 16:31 UTC, annehaley commented on web/src/components/AccessControl.vue
> +const userSelectDialogMode: Ref<string> = ref("add");
True, this was implemented before you had suggested that we constrain Projects in that way. The idea was that projects created by the populate script would exist without an owner until a user claimed ownership. I can remove this feature.

2024-10-10 16:46 UTC, annehaley commented on web/src/components/ProjectConfig.vue
> +          <access-control
True, I usually default to the title case version, but vscode defaults to the snake case version when I use its autocomplete. If I'm being intentional about it, I prefer the title case too. Updated in [ba7fbcf](https://github.com/OpenGeoscience/uvdat/pull/66/commits/ba7fbcfb1e3ac4eb8f6ea22aa5ae6783739ba7b6)

2024-10-10 16:47 UTC, annehaley commented on web/src/components/ProjectConfig.vue
> +      if (selectedProject.value?.id == projectToDelete.value?.id) {
Ok, I just did a simple find-and-replace in [245871b](https://github.com/OpenGeoscience/uvdat/pull/66/commits/245871b2f7b0861443b2a7d619fc43c2b34f028e)

2024-10-10 16:57 UTC, annehaley commented on web/src/components/AccessControl.vue
> +}
Nice, this is more legible. I tested this and observed consistent behavior, so I applied this change in [f5bc7ad](https://github.com/OpenGeoscience/uvdat/pull/66/commits/f5bc7ad65e11b246d01661931323f68c51cf1269).

2024-10-10 16:58 UTC, annehaley commented on web/src/components/AccessControl.vue
> +const userSelectDialogMode: Ref<string> = ref("add");
Applied type suggestion and removed "claim" mode in [816dd25](https://github.com/OpenGeoscience/uvdat/pull/66/commits/816dd2518bd5e5c98049242b5668a068d220a4c1).

2024-10-10 17:16 UTC, annehaley commented on web/src/components/AccessControl.vue
> +            closable-chips
This could still work with a single `v-select` if we add some logic to the update function to ensure that `selectedUsers` is always a list:
```
@update:model-value="
     (v: User | User[]) => {
          if (Array.isArray(v)) selectedUsers = v;
          else selectedUsers = [v];
     }
"
```
Lmk what you think of this solution.

2024-10-10 17:28 UTC, annehaley commented on web/src/components/AccessControl.vue
> +    allUsers.value = data;
I'm not sure that this is the best way to prevent users from having multiple permissions. With this approach, a superuser may want to add themself to a project and wouldn't be able to. Rather, how about I modify `savePermissions` to overwrite any previous permission levels? For example, if a user is already a follower and I add them to the collaborators list, they should be removed from the followers list.

2024-10-10 17:36 UTC, annehaley commented on web/src/components/ProjectConfig.vue
> +      let perm = "view";
Ok, changed in [a843439](https://github.com/OpenGeoscience/uvdat/pull/66/commits/a843439b046ea507f20806c631c89f8d6cac720c)

2024-10-10 17:38 UTC, annehaley commented
The lint failures above are due to an unrelated problem; I have created #82 to resolve it.

2024-10-10 18:14 UTC, jjnesbitt commented on web/src/components/AccessControl.vue
> +            closable-chips
That's a pretty elegant solution! I think technically we're supposed to switch from `v-model` to `:model-value=` if we're manually handling the value updates (since v-model is also trying to update the model-value). But if it works as is I'm not too concerned about it.

2024-10-10 18:36 UTC, jjnesbitt commented on web/src/components/AccessControl.vue
> +    allUsers.value = data;
The most important thing is probably to prevent multiple permissions, so if that's all we can get to, I think that's okay. On that note, I pushed [16e6140](https://github.com/OpenGeoscience/uvdat/pull/66/commits/16e61409b11fec074c7cec673b99c34548323306) to enforce singular permissions on the API, since that's where the real validation should be done. 

I think from the UI perspective, it might be easier to have a separate button on each level, that allows modification for that specific list. Like we have the pencil icon for the owner, we could similarly have that for followers/collaborators, to do the same thing. That would be a pretty intuitive UI, and would allow a nice interface, since you could populate the "selected users" with any users that currently already have that permission already, and easily add/remove people. 

Lmk what you think, definitely not blocking.

2024-10-10 20:18 UTC, annehaley commented on web/src/components/AccessControl.vue
> +            closable-chips
Without realizing it, I actually included this change in [a843439](https://github.com/OpenGeoscience/uvdat/pull/66/commits/a843439b046ea507f20806c631c89f8d6cac720c). Please excuse the accidental commit squashing; I was testing it to write the above comment at the same time I was making the naming changes. This does work as expected even without changing `v-model` to `model-value`. When selecting a new owner in "transfer" mode, the select box will only allow a single selection.

2024-10-10 20:22 UTC, annehaley commented on web/src/components/AccessControl.vue
> +    allUsers.value = data;
Ok, I made additional modifications in [1c83360](https://github.com/OpenGeoscience/uvdat/pull/66/commits/1c83360df559c9eb41bde1a0cfb9c336b4b63658) so that a user can be moved between the follower and collaborator groups easily without that error getting raised. If a user already exists in the followers list and I choose to add them as a collaborator, they will be removed from the followers list and promoted to a collaborator (and vice versa for being demoted from collaborator to follower).

2024-10-10 20:36 UTC, jjnesbitt commented on web/src/components/AccessControl.vue
> +    allUsers.value = data;
It seems i'm still allowed to add the current `owner` of the project to either of those lists, and if I hit submit, i'm presented with the backend error. I think we should remove the current project owner from that list (similar to my original commit but with the owner instead of the current user).

2024-10-10 20:42 UTC, annehaley commented on web/src/components/AccessControl.vue
> +    allUsers.value = data;
Ok, that makes sense. I can't imagine a scenario where the list would need to include the current owner. I made this change in [7051ab4](https://github.com/OpenGeoscience/uvdat/pull/66/commits/7051ab43be0fbaa66eed735b4f3b5b4a675bed74). This also requires an additional step to repopulate `allUsers` after successfully saving permissions, in case the owner has changed.

2024-10-10 21:06 UTC, jjnesbitt commented on web/src/components/AccessControl.vue
> +    allUsers.value = data;
Great, this seems to work as expected.

2024-10-10 21:07 UTC, jjnesbitt approved these changes

2024-10-10 21:13 UTC, merged