Integrate `tile2net` task
OpenGeoscience/uvdat pull request #91
Opened 2024-12-02 16:51 UTC by annehaley

2024-12-12 19:15 UTC, jjnesbitt requested changes

2024-12-12 19:15 UTC, jjnesbitt commented on uvdat/core/tasks/map_layers.py
> +            source = large_image.open(raw_data_path)
I think this function could use some comments as well. It's not really clear to someone reading the code, what the intent of these code blocks are.

2024-12-12 19:15 UTC, jjnesbitt commented on sample_data/use_cases/boston_floods/composite_orthoimagery.py
Where is this file invoked? I don't see it used anywhere.

2024-12-13 17:36 UTC, annehaley commented on web/src/layers.ts
> +    // band: "1",
Thanks for pointing this out. I had commented this out for the (now default) case of using no colormap for a raster, and I didn't test out the colormap functionality. We do need this argument when applying a colormap, so I added this back in for the colormap case in [5511b25](https://github.com/OpenGeoscience/uvdat/pull/91/commits/5511b25db56e52d3cf6e1e632273e03f1b752209).

2024-12-13 17:36 UTC, annehaley commented on uvdat/core/tasks/map_layers.py
>  def create_raster_map_layer(file_item, style_options):
Gotcha, I split this function in [f493c8d](https://github.com/OpenGeoscience/uvdat/pull/91/commits/f493c8da3bda444d3d5c579bdfd5da8a0c946a91)

2024-12-13 17:36 UTC, annehaley commented on uvdat/core/tasks/map_layers.py
> +            source = large_image.open(raw_data_path)
Good idea, I added comments in [f493c8d](https://github.com/OpenGeoscience/uvdat/pull/91/commits/f493c8da3bda444d3d5c579bdfd5da8a0c946a91)

2024-12-13 17:39 UTC, annehaley commented on sample_data/use_cases/boston_floods/composite_orthoimagery.py
You're right, I don't invoke this code anywhere. This is a script that I invoked manually to composite separate raster files into one before using the output file for ingest. I want to keep this code somewhere, though, in case we want to incorporate it into the ingest process more formally later. But that will be dependent on our modelling decisions relating to composite rasters.

2025-01-09 16:36 UTC, jjnesbitt commented on sample_data/use_cases/boston_floods/composite_orthoimagery.py
Maybe this could either be made into a management command, or documented in some way, so that if time passes the inputs and outputs of this script can still be known.

2025-01-09 16:37 UTC, jjnesbitt requested changes
Just left one more comment about the `composite_orthoimagery` script. Otherwise this LGTM

2025-01-10 14:14 UTC, annehaley commented on sample_data/use_cases/boston_floods/composite_orthoimagery.py
Now that I've had some time to explore the new model design in #94, I was able to confirm that we can perform spatial compositiing dynamically (from multiple separate files). Now I know that we won't need this script for our conversion process, as I had been concerned about before. I removed the file in [e3f1f48](https://github.com/OpenGeoscience/uvdat/pull/91/commits/e3f1f48cc51fa05870350e9d5eefd1e9c2803faa), but we can always come back to this PR for the code if it is needed later. 

(If that day ever comes, the usage is very simple. Just put all the target rasters in a folder and change the value for `folder` to point to that path. Then run `python composite_orthoimagery.py` and the result file, `geospatial_composite.tiff`, will be in the target folder.)

2025-01-10 19:12 UTC, merged